import uid from 'uid'

export default [
  {
    activity: 'schwimmen',
    category: 'sport',
    checked: false,
    isBookmarked: false,
    id: uid(),
  },
  {
    activity: 'grillen',
    category: 'group',
    checked: false,
    isBookmarked: false,
    id: uid(),
  },
  {
    activity: 'Paartanz lernen',
    category: 'sport',
    checked: false,
    isBookmarked: false,
    id: uid(),
  },
  {
    activity: 'fotografieren',
    category: 'outdoor',
    checked: false,
    isBookmarked: false,
    id: uid(),
  },
  {
    activity: 'Standup paddeling',
    category: 'sport',
    checked: false,
    isBookmarked: false,
    id: uid(),
  },
  {
    activity: 'Spieleabend',
    category: 'group',
    checked: false,
    isBookmarked: false,
    id: uid(),
  },
  {
    activity: 'Planetarium',
    category: 'indoor',
    checked: false,
    isBookmarked: false,
    id: uid(),
  },
  {
    activity: 'Konzert',
    category: 'outdoor',
    checked: false,
    isBookmarked: false,
    id: uid(),
  },
  {
    activity: 'Theater',
    category: 'indoor',
    checked: false,
    isBookmarked: false,
    id: uid(),
  },
  {
    activity: 'Restaurantbesuch',
    category: 'indoor',
    checked: false,
    isBookmarked: false,
    id: uid(),
  },
  {
    activity: 'Bowlen',
    category: 'group',
    checked: false,
    isBookmarked: false,
    id: uid(),
  },
  {
    activity: 'Wandern',
    category: 'sport',
    checked: false,
    isBookmarked: false,
    id: uid(),
  },
  {
    activity: 'Shoppen',
    category: 'outdoor',
    checked: false,
    isBookmarked: false,
    id: uid(),
  },
  {
    activity: 'Roadtrip',
    category: 'outdoor',
    checked: false,
    isBookmarked: false,
    id: uid(),
  },
]
